apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    user: root
    secureJsonData:
      password: "59252"
    database: weather_db
    jsonData:
      tlsAuth: false
      tlsSkipVerify: true
    isDefault: true
    editable: true